platform :ios, '7.0'

#link_with 'BluetoothObjectFinder', 'BluetoothObjectFinder Tests'

pod 'MagicalRecord', '~> 2.2'
pod "iOS-Slide-Menu"

#http://stackoverflow.com/questions/15284067/cocoapods-turning-magicalrecord-logging-off
#disable magicrecord logging
post_install do |installer|
  installer.project.targets.each do |target|
    target.build_configurations.each do |config|
      s = config.build_settings['GCC_PREPROCESSOR_DEFINITIONS']
    if s==nil then s = [ '$(inherited)' ] end
    s.push('MR_ENABLE_ACTIVE_RECORD_LOGGING=0');
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] = s
    end
  end
end


target :BluetoothObjectFinderTests do
    pod 'MagicalRecord', '~> 2.2'
end

workspace 'BluetoothObjectFinder'